version: '3.4'
volumes:
  sql_data: {}

services:
  FIAP.Pos.Hackathon.Micro.Servico.Processamento.Imagens.Principal.api:
    image: ${DOCKER_REGISTRY-}fiapposhackathonmicroservicoprocessamentoimagensprincipalapi
    depends_on:
      - mongodb
    build:
      context: ../
      dockerfile: Src/Api/Dockerfile
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - sql_data:/data/db
